-- Add up migration script here
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
  viewer_id UUID NOT NULL REFERENCES viewers (id) ON DELETE CASCADE,
  hashed_session_token VARCHAR(100) NOT NULL,
  salt VARCHAR(100) NOT NULL,
  version SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() + INTERVAL '48hours'
);
